onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /cpu_tb/clk
add wave -noupdate /cpu_tb/complete
add wave -noupdate /cpu_tb/rw
add wave -noupdate /cpu_tb/reset
add wave -noupdate /cpu_tb/addr
add wave -noupdate /cpu_tb/data_out
add wave -noupdate /cpu_tb/data_in
add wave -noupdate /cpu_tb/Data
add wave -noupdate /cpu_tb/addr_ideal
add wave -noupdate /cpu_tb/LC3/rd
add wave -noupdate /cpu_tb/LC3/addr
add wave -noupdate /cpu_tb/LC3/din
add wave -noupdate /cpu_tb/LC3/clock
add wave -noupdate /cpu_tb/LC3/reset
add wave -noupdate /cpu_tb/LC3/dout
add wave -noupdate /cpu_tb/LC3/complete
add wave -noupdate /cpu_tb/LC3/F_Control
add wave -noupdate /cpu_tb/LC3/M_Control
add wave -noupdate /cpu_tb/LC3/rd_mem
add wave -noupdate /cpu_tb/LC3/rd_fetch
add wave -noupdate /cpu_tb/LC3/W_Control
add wave -noupdate /cpu_tb/LC3/state
add wave -noupdate /cpu_tb/LC3/C_Control
add wave -noupdate /cpu_tb/LC3/E_Control
add wave -noupdate /cpu_tb/LC3/npc
add wave -noupdate /cpu_tb/LC3/DR_in
add wave -noupdate /cpu_tb/LC3/memout
add wave -noupdate /cpu_tb/LC3/pcout
add wave -noupdate /cpu_tb/LC3/aluout
add wave -noupdate /cpu_tb/LC3/addr_mem
add wave -noupdate /cpu_tb/LC3/addr_fetch
add wave -noupdate /cpu_tb/LC3/D_Data
add wave -noupdate /cpu_tb/LC3/fetch_unit/clock
add wave -noupdate /cpu_tb/LC3/fetch_unit/reset
add wave -noupdate /cpu_tb/LC3/fetch_unit/br_taken
add wave -noupdate /cpu_tb/LC3/fetch_unit/taddr
add wave -noupdate /cpu_tb/LC3/fetch_unit/state
add wave -noupdate /cpu_tb/LC3/fetch_unit/pc
add wave -noupdate /cpu_tb/LC3/fetch_unit/npc
add wave -noupdate /cpu_tb/LC3/fetch_unit/rd
add wave -noupdate /cpu_tb/LC3/fetch_unit/npc_wire
add wave -noupdate /cpu_tb/LC3/fetch_unit/state_mult_out
add wave -noupdate /cpu_tb/LC3/fetch_unit/taddr_mult_out
add wave -noupdate /cpu_tb/LC3/fetch_unit/old_pc
add wave -noupdate /cpu_tb/LC3/fetch_unit/new_pc
add wave -noupdate /cpu_tb/LC3/fetch_unit/new_pc_reg
add wave -noupdate /cpu_tb/LC3/fetch_unit/buffer_control
add wave -noupdate /cpu_tb/LC3/fetch_unit/state_mult_selector
add wave -noupdate /cpu_tb/LC3/decode_unit/clock
add wave -noupdate /cpu_tb/LC3/decode_unit/state
add wave -noupdate /cpu_tb/LC3/decode_unit/dout
add wave -noupdate /cpu_tb/LC3/decode_unit/DR_in
add wave -noupdate /cpu_tb/LC3/decode_unit/M_Control
add wave -noupdate /cpu_tb/LC3/decode_unit/W_Control
add wave -noupdate /cpu_tb/LC3/decode_unit/C_Control
add wave -noupdate /cpu_tb/LC3/decode_unit/E_Control
add wave -noupdate /cpu_tb/LC3/decode_unit/F_Control
add wave -noupdate /cpu_tb/LC3/decode_unit/D_Data
add wave -noupdate /cpu_tb/LC3/decode_unit/i
add wave -noupdate /cpu_tb/LC3/decode_unit/IR
add wave -noupdate /cpu_tb/LC3/decode_unit/dr
add wave -noupdate /cpu_tb/LC3/decode_unit/sr1
add wave -noupdate /cpu_tb/LC3/decode_unit/sr2
add wave -noupdate /cpu_tb/LC3/decode_unit/PSR
add wave -noupdate /cpu_tb/LC3/decode_unit/VSR1
add wave -noupdate /cpu_tb/LC3/decode_unit/VSR2
add wave -noupdate /cpu_tb/LC3/decode_unit/N
add wave -noupdate /cpu_tb/LC3/decode_unit/Z
add wave -noupdate /cpu_tb/LC3/decode_unit/P
add wave -noupdate /cpu_tb/LC3/control_unit/clock
add wave -noupdate /cpu_tb/LC3/control_unit/reset
add wave -noupdate /cpu_tb/LC3/control_unit/complete
add wave -noupdate /cpu_tb/LC3/control_unit/c_control
add wave -noupdate /cpu_tb/LC3/control_unit/state
add wave -noupdate /cpu_tb/LC3/control_unit/type
add wave -noupdate /cpu_tb/LC3/control_unit/memory_access_mode
add wave -noupdate /cpu_tb/LC3/control_unit/store_pc
add wave -noupdate /cpu_tb/LC3/control_unit/load
add wave -noupdate /cpu_tb/LC3/control_unit/current_state
add wave -noupdate /cpu_tb/LC3/control_unit/next_state
add wave -noupdate /cpu_tb/LC3/mem_access_unit/M_addr
add wave -noupdate /cpu_tb/LC3/mem_access_unit/M_Data
add wave -noupdate /cpu_tb/LC3/mem_access_unit/D_out
add wave -noupdate /cpu_tb/LC3/mem_access_unit/State
add wave -noupdate /cpu_tb/LC3/mem_access_unit/M_Control
add wave -noupdate /cpu_tb/LC3/mem_access_unit/rd
add wave -noupdate /cpu_tb/LC3/mem_access_unit/D_in
add wave -noupdate /cpu_tb/LC3/mem_access_unit/memout
add wave -noupdate /cpu_tb/LC3/mem_access_unit/addr
add wave -noupdate /cpu_tb/LC3/mem_access_unit/addr0
add wave -noupdate /cpu_tb/LC3/mem_access_unit/D1
add wave -noupdate /cpu_tb/LC3/mem_access_unit/D0
add wave -noupdate /cpu_tb/LC3/mem_access_unit/C
add wave -noupdate /cpu_tb/LC3/mem_access_unit/TC
add wave -noupdate /cpu_tb/LC3/mem_access_unit/rd0
add wave -noupdate /cpu_tb/LC3/exc_unit/E_control
add wave -noupdate /cpu_tb/LC3/exc_unit/D_data
add wave -noupdate /cpu_tb/LC3/exc_unit/aluout
add wave -noupdate /cpu_tb/LC3/exc_unit/pcout
add wave -noupdate /cpu_tb/LC3/exc_unit/npc
add wave -noupdate /cpu_tb/LC3/exc_unit/aluin2
add wave -noupdate /cpu_tb/LC3/exc_unit/VSR1
add wave -noupdate /cpu_tb/LC3/exc_unit/VSR2
add wave -noupdate /cpu_tb/LC3/exc_unit/IR
add wave -noupdate /cpu_tb/LC3/exc_unit/alu_operation_select
add wave -noupdate /cpu_tb/LC3/exc_unit/pc_sel1
add wave -noupdate /cpu_tb/LC3/exc_unit/pc_sel2
add wave -noupdate /cpu_tb/LC3/exc_unit/op2_sel
add wave -noupdate /cpu_tb/LC3/exc_unit/imm5
add wave -noupdate /cpu_tb/LC3/exc_unit/offset9
add wave -noupdate /cpu_tb/LC3/exc_unit/offset6
add wave -noupdate /cpu_tb/LC3/exc_unit/offset11
add wave -noupdate /cpu_tb/LC3/exc_unit/opr2_pc
add wave -noupdate /cpu_tb/LC3/exc_unit/opr1_pc
add wave -noupdate /cpu_tb/LC3/exc_unit/A1/aluin1
add wave -noupdate /cpu_tb/LC3/exc_unit/A1/aluin2
add wave -noupdate /cpu_tb/LC3/exc_unit/A1/alucontrol
add wave -noupdate /cpu_tb/LC3/exc_unit/A1/aluout
add wave -noupdate /cpu_tb/LC3/writeback_unit/DR_in
add wave -noupdate /cpu_tb/LC3/writeback_unit/aluout
add wave -noupdate /cpu_tb/LC3/writeback_unit/pcout
add wave -noupdate /cpu_tb/LC3/writeback_unit/npc
add wave -noupdate /cpu_tb/LC3/writeback_unit/memout
add wave -noupdate /cpu_tb/LC3/writeback_unit/W_Control
add wave -noupdate /cpu_tb/LC4/Data_in
add wave -noupdate /cpu_tb/LC4/IR
add wave -noupdate /cpu_tb/LC4/Data
add wave -noupdate /cpu_tb/LC4/addr
add wave -noupdate /cpu_tb/LC4/pc
add wave -noupdate /cpu_tb/LC4/Ireg
add wave -noupdate /cpu_tb/LC4/N
add wave -noupdate /cpu_tb/LC4/P
add wave -noupdate /cpu_tb/LC4/Z
add wave -noupdate /cpu_tb/LC4/npc
add wave -noupdate /cpu_tb/CH0/clk
add wave -noupdate /cpu_tb/CH0/rw
add wave -noupdate /cpu_tb/CH0/addr
add wave -noupdate /cpu_tb/CH0/addr_ideal
add wave -noupdate /cpu_tb/CH0/data_out
add wave -noupdate /cpu_tb/CH0/data_in
add wave -noupdate /cpu_tb/CH0/Data
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {0 ps} 0}
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {0 ps} {485888 ps}
